name: python37

channels:
  - nvidia
  - conda-forge
  - defaults

dependencies:
  - python=3.7
  - ipykernel
  # Install cuda libs + ptxas compiler from nvidia channel
  # This will accelerate the compilation of kernels for your specific card
  - cudatoolkit=11
  - cudnn=8
  - cupti=11
  - cuda-nvcc
  - ffmpeg
  - pip
  - pip:
    - tensorflow==2.6.*
    - matplotlib
    - pandas
    - seaborn
    - scikit-learn